// <auto-generated />
using System;
using FloraSync.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FloraSync.Migrations
{
    [DbContext(typeof(FloraSyncContext))]
    [Migration("20250503191658_FiftySeeds")]
    partial class FiftySeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FloraSync.Models.Entities.DiaryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Uploaded")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DiaryImages");
                });

            modelBuilder.Entity("FloraSync.Models.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FunFact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Light")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Water")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FunFact = "Huge road behind draw goal large commercial thank wish wall.",
                            ImageUrl = "/images/monstera_deliciosa.png",
                            Light = 3,
                            Name = "Monstera Deliciosa",
                            Temperature = 4,
                            Type = 3,
                            Water = 2
                        },
                        new
                        {
                            Id = 2,
                            FunFact = "Soldier discussion however without himself can home establish up possible.",
                            ImageUrl = "/images/aloe_vera.png",
                            Light = 0,
                            Name = "Aloe Vera",
                            Temperature = 3,
                            Type = 7,
                            Water = 3
                        },
                        new
                        {
                            Id = 3,
                            FunFact = "Cold identify growth especially threat catch charge meet hour product security television.",
                            ImageUrl = "/images/boston_fern.png",
                            Light = 1,
                            Name = "Boston Fern",
                            Temperature = 2,
                            Type = 7,
                            Water = 4
                        },
                        new
                        {
                            Id = 4,
                            FunFact = "Affect him exactly toward media rock your fill civil development suggest wrong treat.",
                            ImageUrl = "/images/snake_plant.png",
                            Light = 4,
                            Name = "Snake Plant",
                            Temperature = 4,
                            Type = 3,
                            Water = 3
                        },
                        new
                        {
                            Id = 5,
                            FunFact = "Enter politics feeling way special when.",
                            ImageUrl = "/images/peace_lily.png",
                            Light = 4,
                            Name = "Peace Lily",
                            Temperature = 0,
                            Type = 1,
                            Water = 3
                        },
                        new
                        {
                            Id = 6,
                            FunFact = "Bag movie describe red half behind daughter present born likely morning.",
                            ImageUrl = "/images/spider_plant.png",
                            Light = 1,
                            Name = "Spider Plant",
                            Temperature = 1,
                            Type = 1,
                            Water = 1
                        },
                        new
                        {
                            Id = 7,
                            FunFact = "Then exist state toward western guess writer road.",
                            ImageUrl = "/images/jade_plant.png",
                            Light = 2,
                            Name = "Jade Plant",
                            Temperature = 2,
                            Type = 5,
                            Water = 4
                        },
                        new
                        {
                            Id = 8,
                            FunFact = "Sure become of believe result table born effort member early worker woman.",
                            ImageUrl = "/images/english_ivy.png",
                            Light = 2,
                            Name = "English Ivy",
                            Temperature = 1,
                            Type = 7,
                            Water = 0
                        },
                        new
                        {
                            Id = 9,
                            FunFact = "Hold tough identify take report anything agent concern machine structure up around people.",
                            ImageUrl = "/images/zz_plant.png",
                            Light = 2,
                            Name = "ZZ Plant",
                            Temperature = 1,
                            Type = 2,
                            Water = 0
                        },
                        new
                        {
                            Id = 10,
                            FunFact = "Mention scene everyone feeling finally effect stuff.",
                            ImageUrl = "/images/areca_palm.png",
                            Light = 4,
                            Name = "Areca Palm",
                            Temperature = 4,
                            Type = 3,
                            Water = 4
                        },
                        new
                        {
                            Id = 11,
                            FunFact = "Skin large network wait official help or society four there rule.",
                            ImageUrl = "/images/chinese_evergreen.png",
                            Light = 0,
                            Name = "Chinese Evergreen",
                            Temperature = 3,
                            Type = 5,
                            Water = 1
                        },
                        new
                        {
                            Id = 12,
                            FunFact = "Detail see media information high about language.",
                            ImageUrl = "/images/cast_iron_plant.png",
                            Light = 3,
                            Name = "Cast Iron Plant",
                            Temperature = 4,
                            Type = 1,
                            Water = 3
                        },
                        new
                        {
                            Id = 13,
                            FunFact = "Least year professor other sort relate cell range discuss week east pick.",
                            ImageUrl = "/images/bamboo_palm.png",
                            Light = 0,
                            Name = "Bamboo Palm",
                            Temperature = 2,
                            Type = 6,
                            Water = 0
                        },
                        new
                        {
                            Id = 14,
                            FunFact = "Suffer across do international head ready PM about red.",
                            ImageUrl = "/images/philodendron.png",
                            Light = 4,
                            Name = "Philodendron",
                            Temperature = 3,
                            Type = 6,
                            Water = 4
                        },
                        new
                        {
                            Id = 15,
                            FunFact = "Ready ability avoid great black around bag.",
                            ImageUrl = "/images/calathea.png",
                            Light = 4,
                            Name = "Calathea",
                            Temperature = 2,
                            Type = 3,
                            Water = 0
                        },
                        new
                        {
                            Id = 16,
                            FunFact = "Concern check little mention economic support which know.",
                            ImageUrl = "/images/croton.png",
                            Light = 2,
                            Name = "Croton",
                            Temperature = 1,
                            Type = 5,
                            Water = 1
                        },
                        new
                        {
                            Id = 17,
                            FunFact = "Matter thought exist production story PM.",
                            ImageUrl = "/images/rubber_plant.png",
                            Light = 0,
                            Name = "Rubber Plant",
                            Temperature = 4,
                            Type = 4,
                            Water = 0
                        },
                        new
                        {
                            Id = 18,
                            FunFact = "Several in structure activity voice two.",
                            ImageUrl = "/images/pothos.png",
                            Light = 0,
                            Name = "Pothos",
                            Temperature = 3,
                            Type = 5,
                            Water = 4
                        },
                        new
                        {
                            Id = 19,
                            FunFact = "Carry short conference physical because give protect.",
                            ImageUrl = "/images/fiddle_leaf_fig.png",
                            Light = 3,
                            Name = "Fiddle Leaf Fig",
                            Temperature = 0,
                            Type = 3,
                            Water = 4
                        },
                        new
                        {
                            Id = 20,
                            FunFact = "Everybody factor opportunity look time experience develop skin by dream source either address.",
                            ImageUrl = "/images/dracaena.png",
                            Light = 1,
                            Name = "Dracaena",
                            Temperature = 3,
                            Type = 0,
                            Water = 0
                        },
                        new
                        {
                            Id = 21,
                            FunFact = "My skill fire sell probably look fly mind.",
                            ImageUrl = "/images/dieffenbachia.png",
                            Light = 2,
                            Name = "Dieffenbachia",
                            Temperature = 1,
                            Type = 6,
                            Water = 0
                        },
                        new
                        {
                            Id = 22,
                            FunFact = "Glass street anyone save almost everyone feel.",
                            ImageUrl = "/images/bird_of_paradise.png",
                            Light = 3,
                            Name = "Bird of Paradise",
                            Temperature = 1,
                            Type = 5,
                            Water = 4
                        },
                        new
                        {
                            Id = 23,
                            FunFact = "Moment unit can really book hotel defense occur husband.",
                            ImageUrl = "/images/kalanchoe.png",
                            Light = 1,
                            Name = "Kalanchoe",
                            Temperature = 0,
                            Type = 7,
                            Water = 4
                        },
                        new
                        {
                            Id = 24,
                            FunFact = "Majority organization west south Mrs now process student once at rich center.",
                            ImageUrl = "/images/aglaonema.png",
                            Light = 2,
                            Name = "Aglaonema",
                            Temperature = 1,
                            Type = 2,
                            Water = 3
                        },
                        new
                        {
                            Id = 25,
                            FunFact = "As wonder theory able nearly true remain goal recent.",
                            ImageUrl = "/images/oxalis.png",
                            Light = 0,
                            Name = "Oxalis",
                            Temperature = 2,
                            Type = 6,
                            Water = 0
                        },
                        new
                        {
                            Id = 26,
                            FunFact = "Soon check my fall story instead rather fear.",
                            ImageUrl = "/images/begonia.png",
                            Light = 0,
                            Name = "Begonia",
                            Temperature = 0,
                            Type = 4,
                            Water = 2
                        },
                        new
                        {
                            Id = 27,
                            FunFact = "Development son affect order serious quickly.",
                            ImageUrl = "/images/peperomia.png",
                            Light = 0,
                            Name = "Peperomia",
                            Temperature = 4,
                            Type = 1,
                            Water = 0
                        },
                        new
                        {
                            Id = 28,
                            FunFact = "Speak always successful whatever money should able.",
                            ImageUrl = "/images/fittonia.png",
                            Light = 1,
                            Name = "Fittonia",
                            Temperature = 1,
                            Type = 2,
                            Water = 4
                        },
                        new
                        {
                            Id = 29,
                            FunFact = "School she finish Democrat leader know manage between unit else authority.",
                            ImageUrl = "/images/norfolk_island_pine.png",
                            Light = 3,
                            Name = "Norfolk Island Pine",
                            Temperature = 4,
                            Type = 1,
                            Water = 4
                        },
                        new
                        {
                            Id = 30,
                            FunFact = "Three officer necessary score stand effect decision go short its eye.",
                            ImageUrl = "/images/hoya.png",
                            Light = 4,
                            Name = "Hoya",
                            Temperature = 3,
                            Type = 5,
                            Water = 2
                        },
                        new
                        {
                            Id = 31,
                            FunFact = "Address everyone community collection answer still current choose simply hour among class artist.",
                            ImageUrl = "/images/staghorn_fern.png",
                            Light = 4,
                            Name = "Staghorn Fern",
                            Temperature = 2,
                            Type = 2,
                            Water = 2
                        },
                        new
                        {
                            Id = 32,
                            FunFact = "Pay social least agent goal room pressure century indicate this teacher.",
                            ImageUrl = "/images/african_violet.png",
                            Light = 4,
                            Name = "African Violet",
                            Temperature = 2,
                            Type = 2,
                            Water = 3
                        },
                        new
                        {
                            Id = 33,
                            FunFact = "A right during realize watch door risk debate.",
                            ImageUrl = "/images/anthurium.png",
                            Light = 2,
                            Name = "Anthurium",
                            Temperature = 3,
                            Type = 6,
                            Water = 4
                        },
                        new
                        {
                            Id = 34,
                            FunFact = "Capital forward home mean person alone although story score vote evening room.",
                            ImageUrl = "/images/maidenhair_fern.png",
                            Light = 0,
                            Name = "Maidenhair Fern",
                            Temperature = 0,
                            Type = 4,
                            Water = 4
                        },
                        new
                        {
                            Id = 35,
                            FunFact = "Parent become attention example service herself some social baby west according.",
                            ImageUrl = "/images/cordyline.png",
                            Light = 0,
                            Name = "Cordyline",
                            Temperature = 0,
                            Type = 0,
                            Water = 0
                        },
                        new
                        {
                            Id = 36,
                            FunFact = "Bank training heavy price here day sell.",
                            ImageUrl = "/images/polka_dot_plant.png",
                            Light = 3,
                            Name = "Polka Dot Plant",
                            Temperature = 2,
                            Type = 4,
                            Water = 2
                        },
                        new
                        {
                            Id = 37,
                            FunFact = "Trade east agreement none since weight major than high.",
                            ImageUrl = "/images/schefflera.png",
                            Light = 2,
                            Name = "Schefflera",
                            Temperature = 3,
                            Type = 6,
                            Water = 1
                        },
                        new
                        {
                            Id = 38,
                            FunFact = "Could bad low land plant newspaper west discover parent might report federal increase.",
                            ImageUrl = "/images/tradescantia.png",
                            Light = 0,
                            Name = "Tradescantia",
                            Temperature = 2,
                            Type = 0,
                            Water = 1
                        },
                        new
                        {
                            Id = 39,
                            FunFact = "Leave stay fact stock city citizen get beat become drop discover safe movement.",
                            ImageUrl = "/images/tamarind.png",
                            Light = 4,
                            Name = "Tamarind",
                            Temperature = 3,
                            Type = 4,
                            Water = 0
                        },
                        new
                        {
                            Id = 40,
                            FunFact = "Machine wind up different myself ask air toward.",
                            ImageUrl = "/images/chili_pepper.png",
                            Light = 4,
                            Name = "Chili Pepper",
                            Temperature = 2,
                            Type = 0,
                            Water = 3
                        },
                        new
                        {
                            Id = 41,
                            FunFact = "Of list test in civil Mr behind western responsibility like point.",
                            ImageUrl = "/images/rosemary.png",
                            Light = 3,
                            Name = "Rosemary",
                            Temperature = 4,
                            Type = 5,
                            Water = 1
                        },
                        new
                        {
                            Id = 42,
                            FunFact = "Unit bed whatever also reveal responsibility drop raise anything every administration.",
                            ImageUrl = "/images/lavender.png",
                            Light = 3,
                            Name = "Lavender",
                            Temperature = 4,
                            Type = 7,
                            Water = 4
                        },
                        new
                        {
                            Id = 43,
                            FunFact = "Over wait south low individual day.",
                            ImageUrl = "/images/thyme.png",
                            Light = 3,
                            Name = "Thyme",
                            Temperature = 0,
                            Type = 6,
                            Water = 3
                        },
                        new
                        {
                            Id = 44,
                            FunFact = "Project source feeling exactly difficult focus wait specific hour candidate.",
                            ImageUrl = "/images/mint.png",
                            Light = 3,
                            Name = "Mint",
                            Temperature = 0,
                            Type = 7,
                            Water = 3
                        },
                        new
                        {
                            Id = 45,
                            FunFact = "Next man them plan power six defense believe.",
                            ImageUrl = "/images/basil.png",
                            Light = 3,
                            Name = "Basil",
                            Temperature = 0,
                            Type = 0,
                            Water = 1
                        },
                        new
                        {
                            Id = 46,
                            FunFact = "Whose beyond staff wait push hospital.",
                            ImageUrl = "/images/parsley.png",
                            Light = 2,
                            Name = "Parsley",
                            Temperature = 2,
                            Type = 4,
                            Water = 2
                        },
                        new
                        {
                            Id = 47,
                            FunFact = "Tonight act moment since answer her.",
                            ImageUrl = "/images/chamomile.png",
                            Light = 1,
                            Name = "Chamomile",
                            Temperature = 2,
                            Type = 3,
                            Water = 1
                        },
                        new
                        {
                            Id = 48,
                            FunFact = "Author red attention receive authority article member life that point buy.",
                            ImageUrl = "/images/lemon_balm.png",
                            Light = 4,
                            Name = "Lemon Balm",
                            Temperature = 4,
                            Type = 2,
                            Water = 1
                        },
                        new
                        {
                            Id = 49,
                            FunFact = "Voice break anything sign direction them relate.",
                            ImageUrl = "/images/eucalyptus.png",
                            Light = 2,
                            Name = "Eucalyptus",
                            Temperature = 4,
                            Type = 3,
                            Water = 1
                        },
                        new
                        {
                            Id = 50,
                            FunFact = "Room feel environmental case worker too how responsibility.",
                            ImageUrl = "/images/dill.png",
                            Light = 2,
                            Name = "Dill",
                            Temperature = 1,
                            Type = 5,
                            Water = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
