// <auto-generated />
using System;
using FloraSync.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FloraSync.Migrations
{
    [DbContext(typeof(FloraSyncContext))]
    [Migration("20250525150636_FiftySeeds3")]
    partial class FiftySeeds3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FloraSync.Models.Entities.DiaryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Uploaded")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DiaryImages");
                });

            modelBuilder.Entity("FloraSync.Models.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FunFact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Light")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Water")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FunFact = "Monstera leaves develop holes to withstand heavy rainfall.",
                            ImageUrl = "/images/monstera_deliciosa.png",
                            Light = 2,
                            Name = "Monstera Deliciosa",
                            Temperature = 3,
                            Type = 0,
                            Water = 2
                        },
                        new
                        {
                            Id = 2,
                            FunFact = "Aloe vera gel can be used to treat sunburns.",
                            ImageUrl = "/images/aloe_vera.png",
                            Light = 2,
                            Name = "Aloe Vera",
                            Temperature = 3,
                            Type = 1,
                            Water = 0
                        },
                        new
                        {
                            Id = 3,
                            FunFact = "Ferns were around before dinosaurs roamed the earth.",
                            ImageUrl = "/images/boston_fern.png",
                            Light = 4,
                            Name = "Boston Fern",
                            Temperature = 1,
                            Type = 2,
                            Water = 3
                        },
                        new
                        {
                            Id = 4,
                            FunFact = "Its fruit is edible and often used in jams and drinks.",
                            ImageUrl = "/images/prickly_pear.png",
                            Light = 3,
                            Name = "Prickly Pear",
                            Temperature = 3,
                            Type = 3,
                            Water = 0
                        },
                        new
                        {
                            Id = 5,
                            FunFact = "It can bloom even in low light.",
                            ImageUrl = "/images/peace_lily.png",
                            Light = 0,
                            Name = "Peace Lily",
                            Temperature = 2,
                            Type = 4,
                            Water = 2
                        },
                        new
                        {
                            Id = 6,
                            FunFact = "Pothos can grow in water without soil.",
                            ImageUrl = "/images/pothos.png",
                            Light = 0,
                            Name = "Pothos",
                            Temperature = 2,
                            Type = 5,
                            Water = 1
                        },
                        new
                        {
                            Id = 7,
                            FunFact = "Basil is considered a sacred herb in some cultures.",
                            ImageUrl = "/images/basil.png",
                            Light = 2,
                            Name = "Basil",
                            Temperature = 3,
                            Type = 6,
                            Water = 3
                        },
                        new
                        {
                            Id = 8,
                            FunFact = "Air plants don't need soil to grow.",
                            ImageUrl = "/images/tillandsia.png",
                            Light = 2,
                            Name = "Tillandsia",
                            Temperature = 4,
                            Type = 7,
                            Water = 1
                        },
                        new
                        {
                            Id = 9,
                            FunFact = "Fiddle Leaf Figs can grow over 10 feet indoors.",
                            ImageUrl = "/images/fiddle_leaf_fig.png",
                            Light = 2,
                            Name = "Fiddle Leaf Fig",
                            Temperature = 3,
                            Type = 0,
                            Water = 2
                        },
                        new
                        {
                            Id = 10,
                            FunFact = "Jade is considered a symbol of good luck.",
                            ImageUrl = "/images/jade_plant.png",
                            Light = 2,
                            Name = "Jade Plant",
                            Temperature = 3,
                            Type = 1,
                            Water = 1
                        },
                        new
                        {
                            Id = 11,
                            FunFact = "Its fronds resemble a stag’s antlers.",
                            ImageUrl = "/images/staghorn_fern.png",
                            Light = 0,
                            Name = "Staghorn Fern",
                            Temperature = 1,
                            Type = 2,
                            Water = 3
                        },
                        new
                        {
                            Id = 12,
                            FunFact = "It stores water to survive long droughts.",
                            ImageUrl = "/images/barrel_cactus.png",
                            Light = 3,
                            Name = "Barrel Cactus",
                            Temperature = 3,
                            Type = 3,
                            Water = 0
                        },
                        new
                        {
                            Id = 13,
                            FunFact = "Known for its heart-shaped waxy flowers.",
                            ImageUrl = "/images/anthurium.png",
                            Light = 1,
                            Name = "Anthurium",
                            Temperature = 3,
                            Type = 4,
                            Water = 2
                        },
                        new
                        {
                            Id = 14,
                            FunFact = "Each pearl stores water.",
                            ImageUrl = "/images/string_of_pearls.png",
                            Light = 2,
                            Name = "String of Pearls",
                            Temperature = 3,
                            Type = 5,
                            Water = 1
                        },
                        new
                        {
                            Id = 15,
                            FunFact = "Mint can spread quickly and become invasive.",
                            ImageUrl = "/images/mint.png",
                            Light = 2,
                            Name = "Mint",
                            Temperature = 1,
                            Type = 6,
                            Water = 3
                        },
                        new
                        {
                            Id = 16,
                            FunFact = "It gets nutrients from the air.",
                            ImageUrl = "/images/spanish_moss.png",
                            Light = 4,
                            Name = "Spanish Moss",
                            Temperature = 4,
                            Type = 7,
                            Water = 3
                        },
                        new
                        {
                            Id = 17,
                            FunFact = "It can grow up to 100 feet in the wild.",
                            ImageUrl = "/images/rubber_plant.png",
                            Light = 2,
                            Name = "Rubber Plant",
                            Temperature = 3,
                            Type = 0,
                            Water = 2
                        },
                        new
                        {
                            Id = 18,
                            FunFact = "It looks like a tiny zebra-striped aloe.",
                            ImageUrl = "/images/zebra_haworthia.png",
                            Light = 2,
                            Name = "Zebra Haworthia",
                            Temperature = 1,
                            Type = 1,
                            Water = 0
                        },
                        new
                        {
                            Id = 19,
                            FunFact = "Its leaves resemble soft hair.",
                            ImageUrl = "/images/maidenhair_fern.png",
                            Light = 4,
                            Name = "Maidenhair Fern",
                            Temperature = 1,
                            Type = 2,
                            Water = 3
                        },
                        new
                        {
                            Id = 20,
                            FunFact = "It can live for over 30 years.",
                            ImageUrl = "/images/golden_barrel.png",
                            Light = 3,
                            Name = "Golden Barrel",
                            Temperature = 3,
                            Type = 3,
                            Water = 0
                        },
                        new
                        {
                            Id = 21,
                            FunFact = "Orchids have the smallest seeds in the world.",
                            ImageUrl = "/images/orchid.png",
                            Light = 2,
                            Name = "Orchid",
                            Temperature = 4,
                            Type = 4,
                            Water = 2
                        },
                        new
                        {
                            Id = 22,
                            FunFact = "It can climb and cover entire walls.",
                            ImageUrl = "/images/english_ivy.png",
                            Light = 0,
                            Name = "English Ivy",
                            Temperature = 1,
                            Type = 5,
                            Water = 2
                        },
                        new
                        {
                            Id = 23,
                            FunFact = "Cilantro leaves and coriander seeds come from the same plant.",
                            ImageUrl = "/images/cilantro.png",
                            Light = 2,
                            Name = "Cilantro",
                            Temperature = 1,
                            Type = 6,
                            Water = 3
                        },
                        new
                        {
                            Id = 24,
                            FunFact = "It curls its leaves to retain water.",
                            ImageUrl = "/images/bulbosa.png",
                            Light = 2,
                            Name = "Bulbosa",
                            Temperature = 4,
                            Type = 7,
                            Water = 1
                        },
                        new
                        {
                            Id = 25,
                            FunFact = "Leaves close up at night.",
                            ImageUrl = "/images/calathea.png",
                            Light = 4,
                            Name = "Calathea",
                            Temperature = 3,
                            Type = 0,
                            Water = 3
                        },
                        new
                        {
                            Id = 26,
                            FunFact = "Named after a Mexican botanical illustrator.",
                            ImageUrl = "/images/echeveria.png",
                            Light = 3,
                            Name = "Echeveria",
                            Temperature = 3,
                            Type = 1,
                            Water = 0
                        },
                        new
                        {
                            Id = 27,
                            FunFact = "New fronds grow from the center like a bird’s nest.",
                            ImageUrl = "/images/bird’s_nest_fern.png",
                            Light = 0,
                            Name = "Bird’s Nest Fern",
                            Temperature = 1,
                            Type = 2,
                            Water = 3
                        },
                        new
                        {
                            Id = 28,
                            FunFact = "Named for its pad-like shape.",
                            ImageUrl = "/images/bunny_ear_cactus.png",
                            Light = 3,
                            Name = "Bunny Ear Cactus",
                            Temperature = 3,
                            Type = 3,
                            Water = 0
                        },
                        new
                        {
                            Id = 29,
                            FunFact = "There are over 1,000 species.",
                            ImageUrl = "/images/begonia.png",
                            Light = 0,
                            Name = "Begonia",
                            Temperature = 2,
                            Type = 4,
                            Water = 2
                        },
                        new
                        {
                            Id = 30,
                            FunFact = "It spreads easily and fast.",
                            ImageUrl = "/images/creeping_jenny.png",
                            Light = 1,
                            Name = "Creeping Jenny",
                            Temperature = 2,
                            Type = 5,
                            Water = 3
                        },
                        new
                        {
                            Id = 31,
                            FunFact = "Used historically as a memory aid.",
                            ImageUrl = "/images/rosemary.png",
                            Light = 2,
                            Name = "Rosemary",
                            Temperature = 3,
                            Type = 6,
                            Water = 1
                        },
                        new
                        {
                            Id = 32,
                            FunFact = "Its twisted leaves resemble Medusa’s hair.",
                            ImageUrl = "/images/caput_medusae.png",
                            Light = 2,
                            Name = "Caput Medusae",
                            Temperature = 4,
                            Type = 7,
                            Water = 1
                        },
                        new
                        {
                            Id = 33,
                            FunFact = "Can grow without direct sunlight.",
                            ImageUrl = "/images/philodendron.png",
                            Light = 0,
                            Name = "Philodendron",
                            Temperature = 3,
                            Type = 0,
                            Water = 2
                        },
                        new
                        {
                            Id = 34,
                            FunFact = "Fuzzy leaves resemble panda fur.",
                            ImageUrl = "/images/panda_plant.png",
                            Light = 2,
                            Name = "Panda Plant",
                            Temperature = 3,
                            Type = 1,
                            Water = 0
                        },
                        new
                        {
                            Id = 35,
                            FunFact = "Not a true fern!",
                            ImageUrl = "/images/asparagus_fern.png",
                            Light = 4,
                            Name = "Asparagus Fern",
                            Temperature = 1,
                            Type = 2,
                            Water = 3
                        },
                        new
                        {
                            Id = 36,
                            FunFact = "Blooms in winter.",
                            ImageUrl = "/images/christmas_cactus.png",
                            Light = 2,
                            Name = "Christmas Cactus",
                            Temperature = 1,
                            Type = 3,
                            Water = 2
                        },
                        new
                        {
                            Id = 37,
                            FunFact = "Leaves are sensitive to cold water.",
                            ImageUrl = "/images/african_violet.png",
                            Light = 0,
                            Name = "African Violet",
                            Temperature = 1,
                            Type = 4,
                            Water = 2
                        },
                        new
                        {
                            Id = 38,
                            FunFact = "Heart-shaped leaves on vines.",
                            ImageUrl = "/images/string_of_hearts.png",
                            Light = 2,
                            Name = "String of Hearts",
                            Temperature = 2,
                            Type = 5,
                            Water = 1
                        },
                        new
                        {
                            Id = 39,
                            FunFact = "Flowers are edible and tasty.",
                            ImageUrl = "/images/chives.png",
                            Light = 2,
                            Name = "Chives",
                            Temperature = 1,
                            Type = 6,
                            Water = 3
                        },
                        new
                        {
                            Id = 40,
                            FunFact = "Turns red when about to bloom.",
                            ImageUrl = "/images/ionantha.png",
                            Light = 2,
                            Name = "Ionantha",
                            Temperature = 4,
                            Type = 7,
                            Water = 1
                        },
                        new
                        {
                            Id = 41,
                            FunFact = "Also called dumb cane.",
                            ImageUrl = "/images/dieffenbachia.png",
                            Light = 0,
                            Name = "Dieffenbachia",
                            Temperature = 3,
                            Type = 0,
                            Water = 2
                        },
                        new
                        {
                            Id = 42,
                            FunFact = "Offsets look like chicks.",
                            ImageUrl = "/images/hens_and_chicks.png",
                            Light = 2,
                            Name = "Hens and Chicks",
                            Temperature = 0,
                            Type = 1,
                            Water = 0
                        },
                        new
                        {
                            Id = 43,
                            FunFact = "Native to Australia.",
                            ImageUrl = "/images/kangaroo_fern.png",
                            Light = 4,
                            Name = "Kangaroo Fern",
                            Temperature = 1,
                            Type = 2,
                            Water = 3
                        },
                        new
                        {
                            Id = 44,
                            FunFact = "Covered in white hairs.",
                            ImageUrl = "/images/old_man_cactus.png",
                            Light = 3,
                            Name = "Old Man Cactus",
                            Temperature = 3,
                            Type = 3,
                            Water = 0
                        },
                        new
                        {
                            Id = 45,
                            FunFact = "Blooms in many vibrant colors.",
                            ImageUrl = "/images/petunia.png",
                            Light = 2,
                            Name = "Petunia",
                            Temperature = 2,
                            Type = 4,
                            Water = 2
                        },
                        new
                        {
                            Id = 46,
                            FunFact = "Produces baby spiderettes.",
                            ImageUrl = "/images/spider_plant.png",
                            Light = 2,
                            Name = "Spider Plant",
                            Temperature = 2,
                            Type = 5,
                            Water = 2
                        },
                        new
                        {
                            Id = 47,
                            FunFact = "Used for culinary and medicinal purposes.",
                            ImageUrl = "/images/thyme.png",
                            Light = 2,
                            Name = "Thyme",
                            Temperature = 3,
                            Type = 6,
                            Water = 1
                        },
                        new
                        {
                            Id = 48,
                            FunFact = "One of the easiest air plants.",
                            ImageUrl = "/images/stricta.png",
                            Light = 2,
                            Name = "Stricta",
                            Temperature = 4,
                            Type = 7,
                            Water = 1
                        },
                        new
                        {
                            Id = 49,
                            FunFact = "Technically a giant herb, not a tree.",
                            ImageUrl = "/images/banana_plant.png",
                            Light = 2,
                            Name = "Banana Plant",
                            Temperature = 4,
                            Type = 0,
                            Water = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
